// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVJRzpuKPRUpOcWzjGejSccHio3oRRnYI',
    appId: '1:828763240741:web:24f7a82e9bc50e10b442cc',
    messagingSenderId: '828763240741',
    projectId: 'bizorganiza',
    authDomain: 'bizorganiza.firebaseapp.com',
    storageBucket: 'bizorganiza.firebasestorage.app',
    measurementId: 'G-R4PPNSVYJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6jhec7xN07I62a59NfCiiAsd8zrHl5RY',
    appId: '1:828763240741:android:35fd74361488c718b442cc',
    messagingSenderId: '828763240741',
    projectId: 'bizorganiza',
    storageBucket: 'bizorganiza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQHBjhvdhdpuBZAUROY2-IojItdnYdjXc',
    appId: '1:828763240741:ios:d2cbbd3f28a31cf2b442cc',
    messagingSenderId: '828763240741',
    projectId: 'bizorganiza',
    storageBucket: 'bizorganiza.firebasestorage.app',
    iosBundleId: 'com.example.biz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQHBjhvdhdpuBZAUROY2-IojItdnYdjXc',
    appId: '1:828763240741:ios:d2cbbd3f28a31cf2b442cc',
    messagingSenderId: '828763240741',
    projectId: 'bizorganiza',
    storageBucket: 'bizorganiza.firebasestorage.app',
    iosBundleId: 'com.example.biz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVJRzpuKPRUpOcWzjGejSccHio3oRRnYI',
    appId: '1:828763240741:web:3078e16fc4214076b442cc',
    messagingSenderId: '828763240741',
    projectId: 'bizorganiza',
    authDomain: 'bizorganiza.firebaseapp.com',
    storageBucket: 'bizorganiza.firebasestorage.app',
    measurementId: 'G-MY06FCE0ZV',
  );
}
